idle_bg = "#1E1E2E"
idle_fg = "#D9E0EE"
info_bg = "#96CDFB"
info_fg = "#161320"
good_bg = "#ABE9B3"
good_fg = "#161320"
warning_bg = "#FAE3B0"
warning_fg = "#161320"
critical_bg = "#F28FAD"
critical_fg = "#161320"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
