#!/usr/bin/env bash

script_dir=$(pwd)
dry="0"

cd $script_dir
scripts=$(find ./runs -mindepth 1 -maxdepth 1 -executable -type f)

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

copy_dir() {
    from=$1
    to=$2

    pushd $from > /dev/null
    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)

    execute rm $to/$name
    execute cp $from $to/$name
}

link() {
    ln -sf $1 $2
}

copy_dir env/.config $HOME/.config
copy_dir env/.local $HOME/.local

copy_file env/.zshenv $HOME
copy_file env/.zshrc $HOME

link $HOME/.local/share/nvim/bin/nvim $HOME/.local/bin/vi
