#!/usr/bin/env bash

sudo apt autoremove --purge vim snapd -y
sudo apt update
sudo apt upgrade -y
sudo apt autoremove --purge -y
sudo apt install build-essential curl git -y

mkdir -p "$HOME/.local/"{share,state,bin}
mkdir -p "$HOME/.config"
mkdir -p "$HOME/Programming"

git clone https://github.com/Arish-Shah/dev "$HOME/Programming/dev"

pushd "$HOME/Programming/dev" > /dev/null
./run
./dev-env
popd > /dev/null

rm -rf "$HOME/.bash"* \
    "$HOME/.motd_shown" \
    "$HOME/.profile"\
    "$HOME/.wget-hsts"\
    "$HOME/.sudo_as_admin_successful"\
    "$HOME/.landscape"
