#!/usr/bin/env bash

sudo apt-get autoremove --purge -y
sudo apt-get autoclean
sudo apt-get clean
sudo dpkg --configure -a
sudo journalctl --rotate
sudo journalctl --vacuum-time=1s
sudo rm -rf /var/cache/apt/
rm -rf ~/.cache/*
