#!/usr/bin/env bash

sudo apt install build-essential fzf ripgrep -y

curl -LO "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz"

mkdir -p "$HOME/.local/share/nvim"
tar -xzf nvim-linux-x86_64.tar.gz -C "$HOME/.local/share/nvim" --strip-components=1

rm nvim-linux-x86_64.tar.gz
