#!/usr/bin/env bash

export NVM_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvm"
mkdir -p "$NVM_DIR"

export PROFILE=/dev/null
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm install --lts
