#!/usr/bin/env bash

sudo snap remove --purge firefox
sudo snap remove --purge snap-store
sudo snap remove --purge desktop-security-center
sudo snap remove --purge prompting-client
sudo snap remove --purge gnome-42-2204
sudo snap remove --purge gtk-common-themes
sudo snap remove --purge firmware-updater
sudo snap remove --purge bare
sudo snap remove --purge snapd-desktop-integration
sudo snap remove --purge core22
sudo snap remove --purge snapd

sudo systemctl disable snapd.socket
sudo systemctl disable snapd.service
sudo systemctl disable snapd.seeded.service
sudo systemctl disable snapd
sudo systemctl mask snapd

sudo rm -rf /var/cache/snapd/
rm -rf ~/snap

sudo apt autoremove snapd --purge -y
sudo apt-mark hold snapd

echo "\e[1;32m\nSnapd is successfully removed.\n"
