#!/usr/bin/env bash

sudo apt install zsh -y

export ZSH="${XDG_DATA_HOME:-$HOME/.local/share}/oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

sudo chsh -s $(which zsh) $USER
