#!/usr/bin/env bash

sudo apt install zsh -y

sudo chsh -s $(which zsh)

export ZSH="$HOME/.local/share/oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
