theme = "dracula"
icons = "awesome5"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "net"
device = "wlan0"
# format = "{ssid} {speed_down;K*b}"
format = "{ssid}"
interval = 5

[[block]]
block = "backlight"
on_click = "xfce4-power-manager-settings"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used_percents}"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 4000

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
full_format = "{percentage}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
