theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {speed_down;K*b}"
interval = 5

[[block]]
block = "backlight"
minimum = 5
maximum = 100
cycle = [100, 50, 0, 50]

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used_percents}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
full_format = "{percentage}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
