icons = "awesome"

[theme]
file = "catppuccin"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid}"
on_click = "alacritty -e nmtui"
interval = 5

[[block]]
block = "memory"
format_mem = "{mem_used} ({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
full_format = "{percentage}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
