#!/bin/bash

function send_notification() {
  brightness="$(brightnessctl -m | awk -F, '{print substr($4, 0, length($4)-1)}')"
	dunstify -a "brightness" -r 9991 -h int:value:"$brightness" -i xfpm-brightness-lcd "Backlight"
}

case $1 in
up)
	brightnessctl --exponent --quiet set +5%
	send_notification $1
	;;
down)
	brightnessctl --exponent --quiet set 5%-
	send_notification $1
	;;
esac
