#!/bin/bash

function send_notification() {
	volume=$(pamixer --get-volume)
  icon="audio-volume-muted"
  
  if [ "$volume" -lt 25 ] 
  then
      icon="audio-volume-low"
  elif [ "$volume" -lt 75 ] 
  then
      icon="audio-volume-medium"
  else
      icon="audio-volume-high"
  fi
	
  dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "$icon" "Volume: ${volume}%" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	pamixer -u
	pamixer -i 5
	send_notification $1
	;;
down)
	pamixer -u
	pamixer -d 5
	send_notification $1
	;;
mute)
	pamixer -t
	if $(pamixer --get-mute); then
		dunstify -i audio-volume-muted -a "changevolume" -t 2000 -r 9993 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac

# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeVolume"
